all:
  children:
    pve:
      hosts:
        pve-01.home:
          pve__iommu_arch: intel
          pve__hostname: pve-01
          pve__network_interfaces:
            - enp0s3
            - enp0s8
          pve__network_bridges:
            - name: vmbr0
              interfaces: enp0s3
              address: 192.168.11.131/24
              gateway: 192.168.11.1
              description: WAN interface
            - name: vmbr1
              interfaces: enp0s8
              description: LAN interface
          pve__zfs_pools:
            - name: pve01-vm-storage
              pool: vm-storage
        pve-02.home:
          pve__iommu_arch: intel
          pve__hostname: pve-02
          pve__need_dkms: true
          pve__network_interfaces:
            - enp0s5
            - enp0s6
          pve__network_bridges:
            - name: vmbr0
              interfaces: enp0s5
              address: 192.168.11.132/24
              gateway: 192.168.11.1
              description: WAN interface
            - name: vmbr1
              interfaces: enp0s6
              description: LAN interface
          pve__zfs_pools:
            - name: pve02-vm-storage
              pool: vm-storage
      vars:
        pve__admin_password: !unsafe ch4ng3me
        pve__cifs_mounts:
          - name: "vm-backups"
            server: router.home
            share: backups
            username: gringolito
            password: !unsafe ch4ng3me
