---
- name: Configure network interfaces
  ansible.builtin.template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: true
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart network interfaces
# check network configuration template

- name: Configure network interface names
  ansible.builtin.template:
    src: link.j2
    dest: /etc/systemd/network/10-persistent_{{ item.interface_name }}.link
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ pve__network_interface_alias }}"
  when: pve__network_interface_alias is defined
  become: true
  notify: Reboot host
# check interface name template