---
- name: Verify if cluster exists
  ansible.builtin.command: /usr/bin/pvecm status
  register: pve__cluster_status
  check_mode: no
  changed_when: false
  ignore_errors: true
  become: true
  when: pve_cluster_create is defined

- name: Create Proxmox cluster
  become: true
  when: pve_cluster_create is defined and pve_cluster_create not in pve__cluster_status.stdout
  block:
    - name: Create cluster (auto link discover)
      ansible.builtin.command: /usr/bin/pvecm create {{ pve_cluster_create }}
      when: pve_cluster_link is not defined

    - name: Create cluster (manual link0)
      ansible.builtin.command: /usr/bin/pvecm create {{ pve_cluster_create }} --link0 {{ pve_cluster_link }}
      when: pve_cluster_link is defined

- name: Verify cluster membership
  ansible.builtin.command: /usr/bin/pvecm nodes
  register: pve__cluster_nodes
  failed_when: pve__cluster_nodes.rc != 0 and pve__cluster_nodes.rc != 2
  check_mode: no
  changed_when: false
  ignore_errors: true
  become: true
  when: pve_cluster_join_address is defined

- name: Add Proxmox node to the cluster
  become: true
  when: pve_cluster_join_address is defined and (pve__cluster_nodes.rc == 2 or pve_cluster_hostname not in pve__cluster_nodes.stdout)
  block:
    - name: Add node using (auto link discover)
      ansible.builtin.command: /usr/bin/pvecm add {{ pve_cluster_join_address }} --use_ssh
      when: pve_cluster_link is not defined

    - name: Add node to the cluster (manual link0)
      ansible.builtin.command: /usr/bin/pvecm add {{ pve_cluster_join_address }} --link0 {{ pve_cluster_link }} --use_ssh
      when: pve_cluster_link is defined

- name: Configure HA shutdown policy
  ansible.builtin.lineinfile:
    path: /etc/pve/datacenter.cfg
    regexp: "^ha:"
    line: "ha: shutdown_policy={{ pve_cluster_ha_shutdown_policy }}"
    state: present
  when: pve_cluster_ha_shutdown_policy is defined

- name: Configure migration network
  ansible.builtin.lineinfile:
    path: /etc/pve/datacenter.cfg
    regexp: "^migration:"
    line: "migration: network={{ pve_cluster_migration_network }},type=secure"
    state: present
  when: pve_cluster_migration_network is defined
