---
- name: Check for the existing PVE groups
  ansible.builtin.command: /usr/sbin/pveum group list
  register: pve__group_list
  check_mode: no
  changed_when: false
  become: true

- name: Create the Administrators PVE group
  ansible.builtin.command: /usr/sbin/pveum group add {{ pve_admin_group }}
  become: true
  when: pve_admin_group not in pve__group_list.stdout

- name: Assign "Administrator" role to administrator group
  ansible.builtin.command: /usr/sbin/pveum acl modify / --group {{ pve_admin_group }} --roles Administrator
  become: true
  when: pve_admin_group not in pve__group_list.stdout

- name: Create the Auditors PVE group
  ansible.builtin.command: /usr/sbin/pveum group add {{ pve_audit_group }}
  become: true
  when: pve_audit_group not in pve__group_list.stdout

- name: Assign "PVEAuditor" role to auditor group
  ansible.builtin.command: /usr/sbin/pveum acl modify / --group {{ pve_audit_group }} --roles PVEAuditor
  become: true
  when: pve_audit_group not in pve__group_list.stdout

- name: Check for the existing PVE users
  ansible.builtin.command: /usr/sbin/pveum user list
  register: pve__user_list
  check_mode: no
  changed_when: false
  become: true

- name: Create the administrator PVE user and assign to the Administrators group
  ansible.builtin.command: /usr/sbin/pveum user add {{ pve_admin_user }} -password {{ pve_admin_password }} -groups {{ pve_admin_group }}
  become: true
  when: pve_admin_password is defined and pve_admin_user not in pve__user_list.stdout

- name: Create the auditor PVE user and assign to the Auditors group
  ansible.builtin.command: /usr/sbin/pveum user add {{ pve_audit_user }} -password {{ pve_audit_password }} -groups {{ pve_audit_group }}
  become: true
  when: pve__audit_password is defined and pve__audit_user not in pve__user_list.stdout
