---
- name: Update grub
  ansible.builtin.command: update-grub

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all

- name: Reboot host
  ansible.builtin.reboot:
    pre_reboot_delay: 1

- name: Restart iSCSI
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - iscsid
    - open-iscsi

- name: Restart network interfaces
  ansible.builtin.systemd_service:
    name: networking
    state: restarted
